### PR TITLE
Update ccmod.json

### PR DESCRIPTION
**Pull request by krypciak**
Please create a new release

### CODE REVIEW

**Comment by L-Sherry** [comment]
... Why ?

**Comment by krypciak** [comment]
These fields I added are required by the [new `ccmod.json` standard](https://github.com/krypciak/CCModDB/blob/ccmodjson/CCMOD-STANDARD.md).
I'm creating a in-game mod manager that can one-click install mods with all the dependencies, and these fields are required for it to function.

**Comment by krypciak** [comment]
Are these PR's going to happen?
I can put the license field for your `ccmod.json`'s specifically if you so please, but they still won't be in the official standard

**Comment by L-Sherry** [comment]
They will, but testing takes time, and it's not motivating.

**Pull request merged**
